-----------------------------------------------
-----------------------------------------------
--- Clear Materials							---
--- By Paolo Hilario (paolo@cgsoldier.com)	---
--- Created 08.10.06						---
--- http://www.cgsoldier.com				---
--- CGsoldier "Miltitant CG Merc Tools"		---
-----------------------------------------------
-----------------------------------------------

for i = 1 to meditMaterials.count do
	(	
	meditMaterials[i] = VRayMtl ()
	)